In [3]:
import numpy as np
import pandas as pd

In [5]:
# create dataframe
df = pd.DataFrame({
    'A': [1,2,3,4,5,6,7],
    'B': [4,5,6,8,4,1,7]
})

# print first 5 columns
df.head()

   A  B
0  1  4
1  2  5
2  3  6
3  4  8
4  5  4

In [6]:
# create another dataframe
# values generated by numpy

df = pd.DataFrame({
    'A': np.random.normal(loc=2.0, scale=0.4, size=40),
    'B': np.random.normal(loc=3.0, scale=0.1, size=40)
})

# print first 5 columns
df.head()

          A         B
0  1.854804  2.974851
1  2.182934  3.088005
2  1.827795  2.849261
3  2.034664  3.019970
4  1.732140  2.820504

In [8]:
# give data distribution of numerical columns
# describe
df.describe()

               A          B
count  40.000000  40.000000
mean    2.025894   2.994510
std     0.326606   0.095755
min     0.996725   2.771333
25%     1.801241   2.955525
50%     2.078119   3.008138
75%     2.265956   3.071048
max     2.723775   3.160167

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       40 non-null     float64
 1   B       40 non-null     float64
dtypes: float64(2)
memory usage: 768.0 bytes

In [11]:
# get one column
col_A = df['A']
col_A.head()

0    1.854804
1    2.182934
2    1.827795
3    2.034664
4    1.732140
Name: A, dtype: float64