In [1]:
import numpy as np
import pandas as pd

In [3]:
# create dataframe
df = pd.DataFrame({
    'name' : ['A', 'B', 'A', 'B','A', 'B', 'A', 'B'],
    'col_a' : np.random.randint(1,20, size=8),
    'col_b' : np.random.randint(1,20, size=8),
})
df

  name  col_a  col_b
0    A      7     16
1    B     19      1
2    A      6      7
3    B     12      3
4    A     18      2
5    B     16      6
6    A      1     15
7    B      3     17

In [8]:
# groupby categories in `name`
# take sum of values for that category
df.groupby('name')[['col_a', 'col_b']].sum()

      col_a  col_b
name
A        32     40
B        50     27

In [9]:
# groupby categories in `name`
# take mean of values for that category
df.groupby('name')[['col_a', 'col_b']].mean()

      col_a  col_b
name
A       8.0  10.00
B      12.5   6.75